### PR TITLE
[DEV-1.1] rotation of both side

### PR DESCRIPTION
**Pull request by tsaichen-lee**
## Describe Your Change

To make the Tetris be able to rotate both clockwise and counterclockwise, I have created a Rotation strategy interface. 

- IRotation
The IRotation strategy interface contains a method computeNextRotation() for clockwise() class and counterclockwise() class to implement different algorithms for TetrisPiece.

- clockwise() and counterclockwise()
The classes to implement different algorithms.

- Rotation()
This class is to communicate via the IRotation strategy interface; it define the interface of interest to client.

- TetrisPiece
I have add an  attribute "prev" to store the next clockwise rotation piece of the given piece, which means the attribute "next" will store the next counterclockwise rotation piece.
I have add a method prevRotation() which return the prev rotation of the given piece.
In method makefastRotations(), I change the original linked list into a circular double linked list which will link the prev and next pieces of the given piece.

## User story Number
1.1 Rotation

## Checklist before requesting a review
[√] I have performed a self-view of my code.
[√] If it’s a core feature, I have added thorough tests.

### CODE REVIEW

**Review by dimondream — CHANGES_REQUESTED** [review]
The code is easy to understand but some classes did not have comments.

**Comment by clara0510huang** [comment]
Try to add a description in the font of each method you did write and comment. Otherwise, your code is easy to read and the structure of the new function build is clear. Good job.

**Review by clara0510huang — DISMISSED** [review]
Try to add a description in the font of each method you did write and comment. Otherwise, your code is easy to read and the structure of the new function build is clear. Good job.

**Review by dimondream — APPROVED** [review]
Well documented and clear description. Code matches the functionality as described

**Review by clara0510huang — APPROVED** [review]

**Pull request merged**
